export const translations = {
  en: {
    navbar: {
      create: "Create Resume",
      coverLetter: "Cover Letter",
      myResumes: "My Resumes",
      pricing: "Pricing",
      login: "Login",
      logout: "Sign Out",
    },
    builder: {
      personalInfo: "Personal Information",
      workExperience: "Work Experience",
      skills: "Skills",
      education: "Education",
      summary: "Executive Summary",
      preview: "Live Preview",
      download: "Download PDF",
      share: "Public Sharing",
      enhance: "Enhance with AI",
      suggestSkills: "Suggest AI Skills",
    },
    share: {
      verified: "Verified Professional Profile • Generated by CreativeResume.io",
      createOwn: "Create Your Own",
    }
  },
  hi: {
    navbar: {
      create: "रिज्यूमे बनाएं",
      coverLetter: "कवर लेटर",
      myResumes: "मेरे रिज्यूमे",
      pricing: "कीमतें",
      login: "लॉगिन",
      logout: "साइन आउट",
    },
    builder: {
      personalInfo: "व्यक्तिगत जानकारी",
      workExperience: "कार्य अनुभव",
      skills: "कौशल",
      education: "शिक्षा",
      summary: "संक्षिप्त विवरण",
      preview: "लाइव प्रीव्यू",
      download: "PDF डाउनलोड करें",
      share: "सार्वजनिक साझाकरण",
      enhance: "AI से सुधारें",
      suggestSkills: "AI कौशल सुझाव",
    },
    share: {
      verified: "सत्यापित पेशेवर प्रोफाइल • CreativeResume.io द्वारा जनरेट किया गया",
      createOwn: "अपना खुद का बनाएं",
    }
  }
};
